

# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
#baseurl: /path/to/blog 
baseurl: http://breakawaysocialcenter.org/events.html

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: http://breakawaysocialcenter.org/index.html

#### Under the Hood Stuff #####

# Makes pretty (descriptive) permalinks. See Jekyll docs for alternatives.
permalink: pretty

# How many articles do you wish to appear on the front page:
paginate: 20

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown]